version: '2'
services:
  goaws:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    image: goaws
    container_name: goaws
    ports:
      - 4100:4100
    volumes:
     - ./app/conf:/conf
